<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_DisplacementSensor" Id="{7ba37002-a059-4534-9366-2b290f489892}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_DisplacementSensor
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_DisplacementSensor">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>