<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{ffa8b730-dc39-431b-9799-d3bf2636dc18}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbDispSens : FB_DisplacementSensor();
	fbTest : FBtest();
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>